version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/bootcamp/media
    ports:
      - "80:8000"
    depends_on:
      - db